name: 'Checkout PR Head'
description: 'Checkout code from the PR head branch for fork PRs'
runs:
  using: 'composite'
  steps:
    - name: Checkout code from PR head
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }} # Run on the fork branch once approved
      shell: bash
